/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Color = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'none' : IDL.Null,
  'green' : IDL.Null,
  'white' : IDL.Null,
  'yellow' : IDL.Null,
});
export const Point = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const Arc = IDL.Record({
  'center' : Point,
  'endAngle' : IDL.Float64,
  'startAngle' : IDL.Float64,
  'radius' : IDL.Float64,
});
export const Ellipse = IDL.Record({
  'center' : Point,
  'radiusX' : IDL.Float64,
  'radiusY' : IDL.Float64,
});
export const Rectangle = IDL.Record({
  'height' : IDL.Float64,
  'width' : IDL.Float64,
  'topLeft' : Point,
});
export const Polyline = IDL.Record({ 'points' : IDL.Vec(Point) });
export const Line = IDL.Record({ 'end' : Point, 'start' : Point });
export const Circle = IDL.Record({ 'center' : Point, 'radius' : IDL.Float64 });
export const Octagon = IDL.Record({ 'center' : Point, 'size' : IDL.Float64 });
export const DrawingObject = IDL.Variant({
  'arc' : IDL.Record({
    'arc' : Arc,
    'rotation' : IDL.Float64,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'ellipse' : IDL.Record({
    'rotation' : IDL.Float64,
    'ellipse' : Ellipse,
    'fill' : Color,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'filledRectangle' : IDL.Record({
    'rotation' : IDL.Float64,
    'rectangle' : Rectangle,
    'fill' : Color,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'rectangle' : IDL.Record({
    'rotation' : IDL.Float64,
    'rectangle' : Rectangle,
    'fill' : Color,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'polyline' : IDL.Record({
    'rotation' : IDL.Float64,
    'polyline' : Polyline,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'line' : IDL.Record({
    'rotation' : IDL.Float64,
    'line' : Line,
    'color' : Color,
    'layer' : IDL.Nat,
  }),
  'circle' : IDL.Record({
    'rotation' : IDL.Float64,
    'fill' : Color,
    'color' : Color,
    'circle' : Circle,
    'layer' : IDL.Nat,
  }),
  'filledCircle' : IDL.Record({
    'rotation' : IDL.Float64,
    'fill' : Color,
    'color' : Color,
    'circle' : Circle,
    'layer' : IDL.Nat,
  }),
  'octagon' : IDL.Record({
    'rotation' : IDL.Float64,
    'fill' : Color,
    'color' : Color,
    'layer' : IDL.Nat,
    'octagon' : Octagon,
  }),
});
export const Layer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : Color,
  'visible' : IDL.Bool,
});
export const Time = IDL.Int;
export const UnitSystem = IDL.Variant({
  'centimeters' : IDL.Null,
  'pixels' : IDL.Null,
  'inches' : IDL.Null,
});
export const ProjectPublic = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'modified' : Time,
  'name' : IDL.Text,
  'layers' : IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
  'objects' : IDL.Vec(DrawingObject),
  'activeLayer' : IDL.Nat,
  'unitSystem' : UnitSystem,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addLayer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, Color], [IDL.Bool], []),
  'clearAllProjects' : IDL.Func([], [], []),
  'convertToFilledShape' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'createCircle' : IDL.Func(
      [Point, IDL.Float64, Color, IDL.Float64, IDL.Nat],
      [DrawingObject],
      [],
    ),
  'createRectangle' : IDL.Func(
      [Point, IDL.Float64, IDL.Float64, Color, IDL.Float64, IDL.Nat],
      [DrawingObject],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'duplicateProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'editLine' : IDL.Func([IDL.Text, IDL.Nat, Line], [IDL.Bool], []),
  'getAllProjectIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLayers' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Layer))], ['query']),
  'getProjectByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProjectPublic)],
      ['query'],
    ),
  'getProjectCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getProjectMetadata' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'created' : Time,
            'modified' : Time,
            'name' : IDL.Text,
            'unitSystem' : UnitSystem,
          })
        ),
      ],
      ['query'],
    ),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
  'loadProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectPublic)], ['query']),
  'rotateObject' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Bool], []),
  'saveProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(DrawingObject),
        IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
        IDL.Nat,
        UnitSystem,
      ],
      [],
      [],
    ),
  'searchProjectsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectPublic)],
      ['query'],
    ),
  'setActiveLayer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'setFillColor' : IDL.Func([IDL.Text, IDL.Nat, Color], [IDL.Bool], []),
  'setLayerVisibility' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'setUnitSystem' : IDL.Func([IDL.Text, UnitSystem], [IDL.Bool], []),
  'snapToIntersection' : IDL.Func([IDL.Text, Point], [IDL.Opt(Point)], []),
  'updateProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(DrawingObject),
        IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
        IDL.Nat,
        UnitSystem,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Color = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'none' : IDL.Null,
    'green' : IDL.Null,
    'white' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const Point = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const Arc = IDL.Record({
    'center' : Point,
    'endAngle' : IDL.Float64,
    'startAngle' : IDL.Float64,
    'radius' : IDL.Float64,
  });
  const Ellipse = IDL.Record({
    'center' : Point,
    'radiusX' : IDL.Float64,
    'radiusY' : IDL.Float64,
  });
  const Rectangle = IDL.Record({
    'height' : IDL.Float64,
    'width' : IDL.Float64,
    'topLeft' : Point,
  });
  const Polyline = IDL.Record({ 'points' : IDL.Vec(Point) });
  const Line = IDL.Record({ 'end' : Point, 'start' : Point });
  const Circle = IDL.Record({ 'center' : Point, 'radius' : IDL.Float64 });
  const Octagon = IDL.Record({ 'center' : Point, 'size' : IDL.Float64 });
  const DrawingObject = IDL.Variant({
    'arc' : IDL.Record({
      'arc' : Arc,
      'rotation' : IDL.Float64,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'ellipse' : IDL.Record({
      'rotation' : IDL.Float64,
      'ellipse' : Ellipse,
      'fill' : Color,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'filledRectangle' : IDL.Record({
      'rotation' : IDL.Float64,
      'rectangle' : Rectangle,
      'fill' : Color,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'rectangle' : IDL.Record({
      'rotation' : IDL.Float64,
      'rectangle' : Rectangle,
      'fill' : Color,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'polyline' : IDL.Record({
      'rotation' : IDL.Float64,
      'polyline' : Polyline,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'line' : IDL.Record({
      'rotation' : IDL.Float64,
      'line' : Line,
      'color' : Color,
      'layer' : IDL.Nat,
    }),
    'circle' : IDL.Record({
      'rotation' : IDL.Float64,
      'fill' : Color,
      'color' : Color,
      'circle' : Circle,
      'layer' : IDL.Nat,
    }),
    'filledCircle' : IDL.Record({
      'rotation' : IDL.Float64,
      'fill' : Color,
      'color' : Color,
      'circle' : Circle,
      'layer' : IDL.Nat,
    }),
    'octagon' : IDL.Record({
      'rotation' : IDL.Float64,
      'fill' : Color,
      'color' : Color,
      'layer' : IDL.Nat,
      'octagon' : Octagon,
    }),
  });
  const Layer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : Color,
    'visible' : IDL.Bool,
  });
  const Time = IDL.Int;
  const UnitSystem = IDL.Variant({
    'centimeters' : IDL.Null,
    'pixels' : IDL.Null,
    'inches' : IDL.Null,
  });
  const ProjectPublic = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'modified' : Time,
    'name' : IDL.Text,
    'layers' : IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
    'objects' : IDL.Vec(DrawingObject),
    'activeLayer' : IDL.Nat,
    'unitSystem' : UnitSystem,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addLayer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, Color], [IDL.Bool], []),
    'clearAllProjects' : IDL.Func([], [], []),
    'convertToFilledShape' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'createCircle' : IDL.Func(
        [Point, IDL.Float64, Color, IDL.Float64, IDL.Nat],
        [DrawingObject],
        [],
      ),
    'createRectangle' : IDL.Func(
        [Point, IDL.Float64, IDL.Float64, Color, IDL.Float64, IDL.Nat],
        [DrawingObject],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'duplicateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'editLine' : IDL.Func([IDL.Text, IDL.Nat, Line], [IDL.Bool], []),
    'getAllProjectIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLayers' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Layer))], ['query']),
    'getProjectByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProjectPublic)],
        ['query'],
      ),
    'getProjectCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProjectMetadata' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'created' : Time,
              'modified' : Time,
              'name' : IDL.Text,
              'unitSystem' : UnitSystem,
            })
          ),
        ],
        ['query'],
      ),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
    'loadProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectPublic)], ['query']),
    'rotateObject' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [IDL.Bool], []),
    'saveProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(DrawingObject),
          IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
          IDL.Nat,
          UnitSystem,
        ],
        [],
        [],
      ),
    'searchProjectsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectPublic)],
        ['query'],
      ),
    'setActiveLayer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'setFillColor' : IDL.Func([IDL.Text, IDL.Nat, Color], [IDL.Bool], []),
    'setLayerVisibility' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'setUnitSystem' : IDL.Func([IDL.Text, UnitSystem], [IDL.Bool], []),
    'snapToIntersection' : IDL.Func([IDL.Text, Point], [IDL.Opt(Point)], []),
    'updateProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(DrawingObject),
          IDL.Vec(IDL.Tuple(IDL.Nat, Layer)),
          IDL.Nat,
          UnitSystem,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };