/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DrawingObject = {
    __kind__: "arc";
    arc: {
        arc: Arc;
        rotation: number;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "ellipse";
    ellipse: {
        rotation: number;
        ellipse: Ellipse;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "filledRectangle";
    filledRectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "rectangle";
    rectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "polyline";
    polyline: {
        rotation: number;
        polyline: Polyline;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "line";
    line: {
        rotation: number;
        line: Line;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "circle";
    circle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "filledCircle";
    filledCircle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "octagon";
    octagon: {
        rotation: number;
        fill: Color;
        color: Color;
        layer: bigint;
        octagon: Octagon;
    };
};
export interface Circle {
    center: Point;
    radius: number;
}
export interface Arc {
    center: Point;
    endAngle: number;
    startAngle: number;
    radius: number;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Point {
    x: number;
    y: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Rectangle {
    height: number;
    width: number;
    topLeft: Point;
}
export interface Layer {
    id: bigint;
    name: string;
    color: Color;
    visible: boolean;
}
export type Tree = {
    __kind__: "red";
    red: [Tree, bigint, Layer, Tree];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree, bigint, Layer, Tree];
};
export interface Line {
    end: Point;
    start: Point;
}
export interface Polyline {
    points: Array<Point>;
}
export interface Octagon {
    center: Point;
    size: number;
}
export interface Project {
    id: string;
    created: Time;
    modified: Time;
    name: string;
    layers: Map_;
    objects: Array<DrawingObject>;
    activeLayer: bigint;
    unitSystem: UnitSystem;
}
export interface Map_ {
    root: Tree;
    size: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Ellipse {
    center: Point;
    radiusX: number;
    radiusY: number;
}
export enum Color {
    red = "red",
    blue = "blue",
    none = "none",
    green = "green",
    white = "white",
    yellow = "yellow"
}
export enum UnitSystem {
    centimeters = "centimeters",
    pixels = "pixels",
    inches = "inches"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addLayer(projectId: string, layerId: bigint, name: string, color: Color): Promise<boolean>;
    clearAllProjects(): Promise<void>;
    convertToFilledShape(projectId: string, objectIndex: bigint): Promise<boolean>;
    createCircle(center: Point, radius: number, color: Color, rotation: number, layer: bigint): Promise<DrawingObject>;
    createRectangle(topLeft: Point, width: number, height: number, color: Color, rotation: number, layer: bigint): Promise<DrawingObject>;
    deleteProject(id: string): Promise<void>;
    duplicateProject(id: string, newId: string, newName: string): Promise<boolean>;
    editLine(projectId: string, objectIndex: bigint, newLine: Line): Promise<boolean>;
    getAllProjectIds(): Promise<Array<string>>;
    getLayers(projectId: string): Promise<Array<Layer> | null>;
    getProjectByName(name: string): Promise<Project | null>;
    getProjectCount(): Promise<bigint>;
    getProjectMetadata(id: string): Promise<{
        created: Time;
        modified: Time;
        name: string;
        unitSystem: UnitSystem;
    } | null>;
    listProjects(): Promise<Array<Project>>;
    loadProject(id: string): Promise<Project | null>;
    rotateObject(projectId: string, objectIndex: bigint, rotation: number): Promise<boolean>;
    saveProject(id: string, name: string, objects: Array<DrawingObject>, layers: Map_, activeLayer: bigint, unitSystem: UnitSystem): Promise<void>;
    searchProjectsByName(searchTerm: string): Promise<Array<Project>>;
    setActiveLayer(projectId: string, layerId: bigint): Promise<boolean>;
    setFillColor(projectId: string, objectIndex: bigint, fillColor: Color): Promise<boolean>;
    setLayerVisibility(projectId: string, layerId: bigint, visible: boolean): Promise<boolean>;
    setUnitSystem(projectId: string, unitSystem: UnitSystem): Promise<boolean>;
    snapToIntersection(projectId: string, point: Point): Promise<Point | null>;
    updateProject(id: string, objects: Array<DrawingObject>, layers: Map_, activeLayer: bigint, unitSystem: UnitSystem): Promise<boolean>;
}
import type { Arc as _Arc, Circle as _Circle, Color as _Color, DrawingObject as _DrawingObject, Ellipse as _Ellipse, Layer as _Layer, Line as _Line, Map as _Map, Octagon as _Octagon, Point as _Point, Polyline as _Polyline, Project as _Project, Rectangle as _Rectangle, Time as _Time, Tree as _Tree, UnitSystem as _UnitSystem, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addLayer(arg0: string, arg1: bigint, arg2: string, arg3: Color): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addLayer(arg0, arg1, arg2, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLayer(arg0, arg1, arg2, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async clearAllProjects(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllProjects();
            return result;
        }
    }
    async convertToFilledShape(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.convertToFilledShape(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertToFilledShape(arg0, arg1);
            return result;
        }
    }
    async createCircle(arg0: Point, arg1: number, arg2: Color, arg3: number, arg4: bigint): Promise<DrawingObject> {
        if (this.processError) {
            try {
                const result = await this.actor.createCircle(arg0, arg1, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
                return from_candid_DrawingObject_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCircle(arg0, arg1, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg2), arg3, arg4);
            return from_candid_DrawingObject_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async createRectangle(arg0: Point, arg1: number, arg2: number, arg3: Color, arg4: number, arg5: bigint): Promise<DrawingObject> {
        if (this.processError) {
            try {
                const result = await this.actor.createRectangle(arg0, arg1, arg2, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg3), arg4, arg5);
                return from_candid_DrawingObject_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRectangle(arg0, arg1, arg2, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg3), arg4, arg5);
            return from_candid_DrawingObject_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async duplicateProject(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async editLine(arg0: string, arg1: bigint, arg2: Line): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editLine(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editLine(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllProjectIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectIds();
            return result;
        }
    }
    async getLayers(arg0: string): Promise<Array<Layer> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLayers(arg0);
                return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLayers(arg0);
            return from_candid_opt_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProjectByName(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectByName(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectByName(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProjectCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectCount();
            return result;
        }
    }
    async getProjectMetadata(arg0: string): Promise<{
        created: Time;
        modified: Time;
        name: string;
        unitSystem: UnitSystem;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectMetadata(arg0);
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectMetadata(arg0);
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async loadProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loadProject(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadProject(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async rotateObject(arg0: string, arg1: bigint, arg2: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rotateObject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rotateObject(arg0, arg1, arg2);
            return result;
        }
    }
    async saveProject(arg0: string, arg1: string, arg2: Array<DrawingObject>, arg3: Map_, arg4: bigint, arg5: UnitSystem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProject(arg0, arg1, to_candid_vec_n39(this.uploadFile, this.downloadFile, arg2), to_candid_Map_n49(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProject(arg0, arg1, to_candid_vec_n39(this.uploadFile, this.downloadFile, arg2), to_candid_Map_n49(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg5));
            return result;
        }
    }
    async searchProjectsByName(arg0: string): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProjectsByName(arg0);
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProjectsByName(arg0);
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async setActiveLayer(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveLayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveLayer(arg0, arg1);
            return result;
        }
    }
    async setFillColor(arg0: string, arg1: bigint, arg2: Color): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFillColor(arg0, arg1, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFillColor(arg0, arg1, to_candid_Color_n8(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async setLayerVisibility(arg0: string, arg1: bigint, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setLayerVisibility(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLayerVisibility(arg0, arg1, arg2);
            return result;
        }
    }
    async setUnitSystem(arg0: string, arg1: UnitSystem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUnitSystem(arg0, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUnitSystem(arg0, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async snapToIntersection(arg0: string, arg1: Point): Promise<Point | null> {
        if (this.processError) {
            try {
                const result = await this.actor.snapToIntersection(arg0, arg1);
                return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.snapToIntersection(arg0, arg1);
            return from_candid_opt_n58(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateProject(arg0: string, arg1: Array<DrawingObject>, arg2: Map_, arg3: bigint, arg4: UnitSystem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_vec_n39(this.uploadFile, this.downloadFile, arg1), to_candid_Map_n49(this.uploadFile, this.downloadFile, arg2), arg3, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_vec_n39(this.uploadFile, this.downloadFile, arg1), to_candid_Map_n49(this.uploadFile, this.downloadFile, arg2), arg3, to_candid_UnitSystem_n56(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_Color_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Color): Color {
    return from_candid_variant_n14(uploadFile, downloadFile, value);
}
function from_candid_DrawingObject_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawingObject): DrawingObject {
    return from_candid_variant_n11(uploadFile, downloadFile, value);
}
function from_candid_Layer_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Layer): Layer {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_Map_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Map): Map_ {
    return from_candid_record_n29(uploadFile, downloadFile, value);
}
function from_candid_Project_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid_Tree_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tree): Tree {
    return from_candid_variant_n31(uploadFile, downloadFile, value);
}
function from_candid_UnitSystem_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnitSystem): UnitSystem {
    return from_candid_variant_n35(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Layer>]): Array<Layer> | null {
    return value.length === 0 ? null : from_candid_vec_n22(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n26(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        created: _Time;
        modified: _Time;
        name: string;
        unitSystem: _UnitSystem;
    }]): {
    created: Time;
    modified: Time;
    name: string;
    unitSystem: UnitSystem;
} | null {
    return value.length === 0 ? null : from_candid_record_n37(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Point]): Point | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arc: _Arc;
    rotation: number;
    color: _Color;
    layer: bigint;
}): {
    arc: Arc;
    rotation: number;
    color: Color;
    layer: bigint;
} {
    return {
        arc: value.arc,
        rotation: value.rotation,
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    ellipse: _Ellipse;
    fill: _Color;
    color: _Color;
    layer: bigint;
}): {
    rotation: number;
    ellipse: Ellipse;
    fill: Color;
    color: Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        ellipse: value.ellipse,
        fill: from_candid_Color_n13(uploadFile, downloadFile, value.fill),
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function from_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    rectangle: _Rectangle;
    fill: _Color;
    color: _Color;
    layer: bigint;
}): {
    rotation: number;
    rectangle: Rectangle;
    fill: Color;
    color: Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        rectangle: value.rectangle,
        fill: from_candid_Color_n13(uploadFile, downloadFile, value.fill),
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    polyline: _Polyline;
    color: _Color;
    layer: bigint;
}): {
    rotation: number;
    polyline: Polyline;
    color: Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        polyline: value.polyline,
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    line: _Line;
    color: _Color;
    layer: bigint;
}): {
    rotation: number;
    line: Line;
    color: Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        line: value.line,
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    fill: _Color;
    color: _Color;
    circle: _Circle;
    layer: bigint;
}): {
    rotation: number;
    fill: Color;
    color: Color;
    circle: Circle;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        fill: from_candid_Color_n13(uploadFile, downloadFile, value.fill),
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        circle: value.circle,
        layer: value.layer
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    fill: _Color;
    color: _Color;
    layer: bigint;
    octagon: _Octagon;
}): {
    rotation: number;
    fill: Color;
    color: Color;
    layer: bigint;
    octagon: Octagon;
} {
    return {
        rotation: value.rotation,
        fill: from_candid_Color_n13(uploadFile, downloadFile, value.fill),
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        layer: value.layer,
        octagon: value.octagon
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    color: _Color;
    visible: boolean;
}): {
    id: bigint;
    name: string;
    color: Color;
    visible: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        color: from_candid_Color_n13(uploadFile, downloadFile, value.color),
        visible: value.visible
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: _Time;
    modified: _Time;
    name: string;
    layers: _Map;
    objects: Array<_DrawingObject>;
    activeLayer: bigint;
    unitSystem: _UnitSystem;
}): {
    id: string;
    created: Time;
    modified: Time;
    name: string;
    layers: Map_;
    objects: Array<DrawingObject>;
    activeLayer: bigint;
    unitSystem: UnitSystem;
} {
    return {
        id: value.id,
        created: value.created,
        modified: value.modified,
        name: value.name,
        layers: from_candid_Map_n28(uploadFile, downloadFile, value.layers),
        objects: from_candid_vec_n33(uploadFile, downloadFile, value.objects),
        activeLayer: value.activeLayer,
        unitSystem: from_candid_UnitSystem_n34(uploadFile, downloadFile, value.unitSystem)
    };
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: _Tree;
    size: bigint;
}): {
    root: Tree;
    size: bigint;
} {
    return {
        root: from_candid_Tree_n30(uploadFile, downloadFile, value.root),
        size: value.size
    };
}
function from_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    modified: _Time;
    name: string;
    unitSystem: _UnitSystem;
}): {
    created: Time;
    modified: Time;
    name: string;
    unitSystem: UnitSystem;
} {
    return {
        created: value.created,
        modified: value.modified,
        name: value.name,
        unitSystem: from_candid_UnitSystem_n34(uploadFile, downloadFile, value.unitSystem)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Tree, bigint, _Layer, _Tree]): [Tree, bigint, Layer, Tree] {
    return [
        from_candid_Tree_n30(uploadFile, downloadFile, value[0]),
        value[1],
        from_candid_Layer_n23(uploadFile, downloadFile, value[2]),
        from_candid_Tree_n30(uploadFile, downloadFile, value[3])
    ];
}
function from_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arc: {
        arc: _Arc;
        rotation: number;
        color: _Color;
        layer: bigint;
    };
} | {
    ellipse: {
        rotation: number;
        ellipse: _Ellipse;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    filledRectangle: {
        rotation: number;
        rectangle: _Rectangle;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    rectangle: {
        rotation: number;
        rectangle: _Rectangle;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    polyline: {
        rotation: number;
        polyline: _Polyline;
        color: _Color;
        layer: bigint;
    };
} | {
    line: {
        rotation: number;
        line: _Line;
        color: _Color;
        layer: bigint;
    };
} | {
    circle: {
        rotation: number;
        fill: _Color;
        color: _Color;
        circle: _Circle;
        layer: bigint;
    };
} | {
    filledCircle: {
        rotation: number;
        fill: _Color;
        color: _Color;
        circle: _Circle;
        layer: bigint;
    };
} | {
    octagon: {
        rotation: number;
        fill: _Color;
        color: _Color;
        layer: bigint;
        octagon: _Octagon;
    };
}): {
    __kind__: "arc";
    arc: {
        arc: Arc;
        rotation: number;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "ellipse";
    ellipse: {
        rotation: number;
        ellipse: Ellipse;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "filledRectangle";
    filledRectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "rectangle";
    rectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "polyline";
    polyline: {
        rotation: number;
        polyline: Polyline;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "line";
    line: {
        rotation: number;
        line: Line;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "circle";
    circle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "filledCircle";
    filledCircle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "octagon";
    octagon: {
        rotation: number;
        fill: Color;
        color: Color;
        layer: bigint;
        octagon: Octagon;
    };
} {
    return "arc" in value ? {
        __kind__: "arc",
        arc: from_candid_record_n12(uploadFile, downloadFile, value.arc)
    } : "ellipse" in value ? {
        __kind__: "ellipse",
        ellipse: from_candid_record_n15(uploadFile, downloadFile, value.ellipse)
    } : "filledRectangle" in value ? {
        __kind__: "filledRectangle",
        filledRectangle: from_candid_record_n16(uploadFile, downloadFile, value.filledRectangle)
    } : "rectangle" in value ? {
        __kind__: "rectangle",
        rectangle: from_candid_record_n16(uploadFile, downloadFile, value.rectangle)
    } : "polyline" in value ? {
        __kind__: "polyline",
        polyline: from_candid_record_n17(uploadFile, downloadFile, value.polyline)
    } : "line" in value ? {
        __kind__: "line",
        line: from_candid_record_n18(uploadFile, downloadFile, value.line)
    } : "circle" in value ? {
        __kind__: "circle",
        circle: from_candid_record_n19(uploadFile, downloadFile, value.circle)
    } : "filledCircle" in value ? {
        __kind__: "filledCircle",
        filledCircle: from_candid_record_n19(uploadFile, downloadFile, value.filledCircle)
    } : "octagon" in value ? {
        __kind__: "octagon",
        octagon: from_candid_record_n20(uploadFile, downloadFile, value.octagon)
    } : value;
}
function from_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    none: null;
} | {
    green: null;
} | {
    white: null;
} | {
    yellow: null;
}): Color {
    return "red" in value ? Color.red : "blue" in value ? Color.blue : "none" in value ? Color.none : "green" in value ? Color.green : "white" in value ? Color.white : "yellow" in value ? Color.yellow : value;
}
function from_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: [_Tree, bigint, _Layer, _Tree];
} | {
    leaf: null;
} | {
    black: [_Tree, bigint, _Layer, _Tree];
}): {
    __kind__: "red";
    red: [Tree, bigint, Layer, Tree];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree, bigint, Layer, Tree];
} {
    return "red" in value ? {
        __kind__: "red",
        red: from_candid_tuple_n32(uploadFile, downloadFile, value.red)
    } : "leaf" in value ? {
        __kind__: "leaf",
        leaf: value.leaf
    } : "black" in value ? {
        __kind__: "black",
        black: from_candid_tuple_n32(uploadFile, downloadFile, value.black)
    } : value;
}
function from_candid_variant_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    centimeters: null;
} | {
    pixels: null;
} | {
    inches: null;
}): UnitSystem {
    return "centimeters" in value ? UnitSystem.centimeters : "pixels" in value ? UnitSystem.pixels : "inches" in value ? UnitSystem.inches : value;
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Layer>): Array<Layer> {
    return value.map((x)=>from_candid_Layer_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DrawingObject>): Array<DrawingObject> {
    return value.map((x)=>from_candid_DrawingObject_n10(uploadFile, downloadFile, x));
}
function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n26(uploadFile, downloadFile, x));
}
function to_candid_Color_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): _Color {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_DrawingObject_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawingObject): _DrawingObject {
    return to_candid_variant_n41(uploadFile, downloadFile, value);
}
function to_candid_Layer_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Layer): _Layer {
    return to_candid_record_n55(uploadFile, downloadFile, value);
}
function to_candid_Map_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Map_): _Map {
    return to_candid_record_n50(uploadFile, downloadFile, value);
}
function to_candid_Tree_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tree): _Tree {
    return to_candid_variant_n52(uploadFile, downloadFile, value);
}
function to_candid_UnitSystem_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnitSystem): _UnitSystem {
    return to_candid_variant_n57(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    fill: Color;
    color: Color;
    layer: bigint;
    octagon: Octagon;
}): {
    rotation: number;
    fill: _Color;
    color: _Color;
    layer: bigint;
    octagon: _Octagon;
} {
    return {
        rotation: value.rotation,
        fill: to_candid_Color_n8(uploadFile, downloadFile, value.fill),
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer,
        octagon: value.octagon
    };
}
function to_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    fill: Color;
    color: Color;
    circle: Circle;
    layer: bigint;
}): {
    rotation: number;
    fill: _Color;
    color: _Color;
    circle: _Circle;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        fill: to_candid_Color_n8(uploadFile, downloadFile, value.fill),
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        circle: value.circle,
        layer: value.layer
    };
}
function to_candid_record_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    line: Line;
    color: Color;
    layer: bigint;
}): {
    rotation: number;
    line: _Line;
    color: _Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        line: value.line,
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function to_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    polyline: Polyline;
    color: Color;
    layer: bigint;
}): {
    rotation: number;
    polyline: _Polyline;
    color: _Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        polyline: value.polyline,
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function to_candid_record_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    rectangle: Rectangle;
    fill: Color;
    color: Color;
    layer: bigint;
}): {
    rotation: number;
    rectangle: _Rectangle;
    fill: _Color;
    color: _Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        rectangle: value.rectangle,
        fill: to_candid_Color_n8(uploadFile, downloadFile, value.fill),
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function to_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: number;
    ellipse: Ellipse;
    fill: Color;
    color: Color;
    layer: bigint;
}): {
    rotation: number;
    ellipse: _Ellipse;
    fill: _Color;
    color: _Color;
    layer: bigint;
} {
    return {
        rotation: value.rotation,
        ellipse: value.ellipse,
        fill: to_candid_Color_n8(uploadFile, downloadFile, value.fill),
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function to_candid_record_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arc: Arc;
    rotation: number;
    color: Color;
    layer: bigint;
}): {
    arc: _Arc;
    rotation: number;
    color: _Color;
    layer: bigint;
} {
    return {
        arc: value.arc,
        rotation: value.rotation,
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        layer: value.layer
    };
}
function to_candid_record_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    root: Tree;
    size: bigint;
}): {
    root: _Tree;
    size: bigint;
} {
    return {
        root: to_candid_Tree_n51(uploadFile, downloadFile, value.root),
        size: value.size
    };
}
function to_candid_record_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    color: Color;
    visible: boolean;
}): {
    id: bigint;
    name: string;
    color: _Color;
    visible: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        color: to_candid_Color_n8(uploadFile, downloadFile, value.color),
        visible: value.visible
    };
}
function to_candid_tuple_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Tree, bigint, Layer, Tree]): [_Tree, bigint, _Layer, _Tree] {
    return [
        to_candid_Tree_n51(uploadFile, downloadFile, value[0]),
        value[1],
        to_candid_Layer_n54(uploadFile, downloadFile, value[2]),
        to_candid_Tree_n51(uploadFile, downloadFile, value[3])
    ];
}
function to_candid_variant_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "arc";
    arc: {
        arc: Arc;
        rotation: number;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "ellipse";
    ellipse: {
        rotation: number;
        ellipse: Ellipse;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "filledRectangle";
    filledRectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "rectangle";
    rectangle: {
        rotation: number;
        rectangle: Rectangle;
        fill: Color;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "polyline";
    polyline: {
        rotation: number;
        polyline: Polyline;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "line";
    line: {
        rotation: number;
        line: Line;
        color: Color;
        layer: bigint;
    };
} | {
    __kind__: "circle";
    circle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "filledCircle";
    filledCircle: {
        rotation: number;
        fill: Color;
        color: Color;
        circle: Circle;
        layer: bigint;
    };
} | {
    __kind__: "octagon";
    octagon: {
        rotation: number;
        fill: Color;
        color: Color;
        layer: bigint;
        octagon: Octagon;
    };
}): {
    arc: {
        arc: _Arc;
        rotation: number;
        color: _Color;
        layer: bigint;
    };
} | {
    ellipse: {
        rotation: number;
        ellipse: _Ellipse;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    filledRectangle: {
        rotation: number;
        rectangle: _Rectangle;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    rectangle: {
        rotation: number;
        rectangle: _Rectangle;
        fill: _Color;
        color: _Color;
        layer: bigint;
    };
} | {
    polyline: {
        rotation: number;
        polyline: _Polyline;
        color: _Color;
        layer: bigint;
    };
} | {
    line: {
        rotation: number;
        line: _Line;
        color: _Color;
        layer: bigint;
    };
} | {
    circle: {
        rotation: number;
        fill: _Color;
        color: _Color;
        circle: _Circle;
        layer: bigint;
    };
} | {
    filledCircle: {
        rotation: number;
        fill: _Color;
        color: _Color;
        circle: _Circle;
        layer: bigint;
    };
} | {
    octagon: {
        rotation: number;
        fill: _Color;
        color: _Color;
        layer: bigint;
        octagon: _Octagon;
    };
} {
    return value.__kind__ === "arc" ? {
        arc: to_candid_record_n48(uploadFile, downloadFile, value.arc)
    } : value.__kind__ === "ellipse" ? {
        ellipse: to_candid_record_n47(uploadFile, downloadFile, value.ellipse)
    } : value.__kind__ === "filledRectangle" ? {
        filledRectangle: to_candid_record_n46(uploadFile, downloadFile, value.filledRectangle)
    } : value.__kind__ === "rectangle" ? {
        rectangle: to_candid_record_n46(uploadFile, downloadFile, value.rectangle)
    } : value.__kind__ === "polyline" ? {
        polyline: to_candid_record_n45(uploadFile, downloadFile, value.polyline)
    } : value.__kind__ === "line" ? {
        line: to_candid_record_n44(uploadFile, downloadFile, value.line)
    } : value.__kind__ === "circle" ? {
        circle: to_candid_record_n43(uploadFile, downloadFile, value.circle)
    } : value.__kind__ === "filledCircle" ? {
        filledCircle: to_candid_record_n43(uploadFile, downloadFile, value.filledCircle)
    } : value.__kind__ === "octagon" ? {
        octagon: to_candid_record_n42(uploadFile, downloadFile, value.octagon)
    } : value;
}
function to_candid_variant_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "red";
    red: [Tree, bigint, Layer, Tree];
} | {
    __kind__: "leaf";
    leaf: null;
} | {
    __kind__: "black";
    black: [Tree, bigint, Layer, Tree];
}): {
    red: [_Tree, bigint, _Layer, _Tree];
} | {
    leaf: null;
} | {
    black: [_Tree, bigint, _Layer, _Tree];
} {
    return value.__kind__ === "red" ? {
        red: to_candid_tuple_n53(uploadFile, downloadFile, value.red)
    } : value.__kind__ === "leaf" ? {
        leaf: value.leaf
    } : value.__kind__ === "black" ? {
        black: to_candid_tuple_n53(uploadFile, downloadFile, value.black)
    } : value;
}
function to_candid_variant_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnitSystem): {
    centimeters: null;
} | {
    pixels: null;
} | {
    inches: null;
} {
    return value == UnitSystem.centimeters ? {
        centimeters: null
    } : value == UnitSystem.pixels ? {
        pixels: null
    } : value == UnitSystem.inches ? {
        inches: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): {
    red: null;
} | {
    blue: null;
} | {
    none: null;
} | {
    green: null;
} | {
    white: null;
} | {
    yellow: null;
} {
    return value == Color.red ? {
        red: null
    } : value == Color.blue ? {
        blue: null
    } : value == Color.none ? {
        none: null
    } : value == Color.green ? {
        green: null
    } : value == Color.white ? {
        white: null
    } : value == Color.yellow ? {
        yellow: null
    } : value;
}
function to_candid_vec_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DrawingObject>): Array<_DrawingObject> {
    return value.map((x)=>to_candid_DrawingObject_n40(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}