/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Arc {
  'center' : Point,
  'endAngle' : number,
  'startAngle' : number,
  'radius' : number,
}
export interface Circle { 'center' : Point, 'radius' : number }
export type Color = { 'red' : null } |
  { 'blue' : null } |
  { 'none' : null } |
  { 'green' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export type DrawingObject = {
    'arc' : {
      'arc' : Arc,
      'rotation' : number,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'ellipse' : {
      'rotation' : number,
      'ellipse' : Ellipse,
      'fill' : Color,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'filledRectangle' : {
      'rotation' : number,
      'rectangle' : Rectangle,
      'fill' : Color,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'rectangle' : {
      'rotation' : number,
      'rectangle' : Rectangle,
      'fill' : Color,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'polyline' : {
      'rotation' : number,
      'polyline' : Polyline,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'line' : {
      'rotation' : number,
      'line' : Line,
      'color' : Color,
      'layer' : bigint,
    }
  } |
  {
    'circle' : {
      'rotation' : number,
      'fill' : Color,
      'color' : Color,
      'circle' : Circle,
      'layer' : bigint,
    }
  } |
  {
    'filledCircle' : {
      'rotation' : number,
      'fill' : Color,
      'color' : Color,
      'circle' : Circle,
      'layer' : bigint,
    }
  } |
  {
    'octagon' : {
      'rotation' : number,
      'fill' : Color,
      'color' : Color,
      'layer' : bigint,
      'octagon' : Octagon,
    }
  };
export interface Ellipse {
  'center' : Point,
  'radiusX' : number,
  'radiusY' : number,
}
export interface Layer {
  'id' : bigint,
  'name' : string,
  'color' : Color,
  'visible' : boolean,
}
export interface Line { 'end' : Point, 'start' : Point }
export interface Map { 'root' : Tree, 'size' : bigint }
export interface Octagon { 'center' : Point, 'size' : number }
export interface Point { 'x' : number, 'y' : number }
export interface Polyline { 'points' : Array<Point> }
export interface Project {
  'id' : string,
  'created' : Time,
  'modified' : Time,
  'name' : string,
  'layers' : Map,
  'objects' : Array<DrawingObject>,
  'activeLayer' : bigint,
  'unitSystem' : UnitSystem,
}
export interface Rectangle {
  'height' : number,
  'width' : number,
  'topLeft' : Point,
}
export type Time = bigint;
export type Tree = { 'red' : [Tree, bigint, Layer, Tree] } |
  { 'leaf' : null } |
  { 'black' : [Tree, bigint, Layer, Tree] };
export type UnitSystem = { 'centimeters' : null } |
  { 'pixels' : null } |
  { 'inches' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addLayer' : ActorMethod<[string, bigint, string, Color], boolean>,
  'clearAllProjects' : ActorMethod<[], undefined>,
  'convertToFilledShape' : ActorMethod<[string, bigint], boolean>,
  'createCircle' : ActorMethod<
    [Point, number, Color, number, bigint],
    DrawingObject
  >,
  'createRectangle' : ActorMethod<
    [Point, number, number, Color, number, bigint],
    DrawingObject
  >,
  'deleteProject' : ActorMethod<[string], undefined>,
  'duplicateProject' : ActorMethod<[string, string, string], boolean>,
  'editLine' : ActorMethod<[string, bigint, Line], boolean>,
  'getAllProjectIds' : ActorMethod<[], Array<string>>,
  'getLayers' : ActorMethod<[string], [] | [Array<Layer>]>,
  'getProjectByName' : ActorMethod<[string], [] | [Project]>,
  'getProjectCount' : ActorMethod<[], bigint>,
  'getProjectMetadata' : ActorMethod<
    [string],
    [] | [
      {
        'created' : Time,
        'modified' : Time,
        'name' : string,
        'unitSystem' : UnitSystem,
      }
    ]
  >,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'loadProject' : ActorMethod<[string], [] | [Project]>,
  'rotateObject' : ActorMethod<[string, bigint, number], boolean>,
  'saveProject' : ActorMethod<
    [string, string, Array<DrawingObject>, Map, bigint, UnitSystem],
    undefined
  >,
  'searchProjectsByName' : ActorMethod<[string], Array<Project>>,
  'setActiveLayer' : ActorMethod<[string, bigint], boolean>,
  'setFillColor' : ActorMethod<[string, bigint, Color], boolean>,
  'setLayerVisibility' : ActorMethod<[string, bigint, boolean], boolean>,
  'setUnitSystem' : ActorMethod<[string, UnitSystem], boolean>,
  'snapToIntersection' : ActorMethod<[string, Point], [] | [Point]>,
  'updateProject' : ActorMethod<
    [string, Array<DrawingObject>, Map, bigint, UnitSystem],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];